depth=18;
image_speed=0;
y=instance_nearest(x,y, oZemin).bbox_top;
x=instance_nearest(x,y,oElevator).bbox_left
gidis=3;
sure=60;
pressed=false;
paragelir=false;
paraanim=60;
timer=29;
seviye=0;
can=20;